development:
  secret_token:    <%= ('x' * 30) %>
  secret_key_base: <%= ('x' * 30) %>

test:
  secret_token:    <%= ('x' * 30) %>
  secret_key_base: <%= ('x' * 30) %>

production:
  secret_token:    <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>